# Generated by Django 6.0.6 on 2026-07-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_add_joined_at_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meeting',
            new_name='scheduler_m_date_adf29a_idx',
            old_name='scheduler_m_date_613e7a_idx',
        ),
        migrations.RenameIndex(
            model_name='meeting',
            new_name='scheduler_m_room_id_e42168_idx',
            old_name='scheduler_m_room_id_09d574_idx',
        ),
    ]
